### ISSUE TITLE
save mapped shorelines

### ISSUE THREAD

**Issue by bruna-ambrosio** [kvos/CoastSat#157]
Hi Kilian (@kvos),

I hope you’re doing well.

I have a question about how the mapped shorelines are saved in the geojson file. I would like to save my coastlines separately to open them in a software like Arcgis and make some changes in regions where the detection has errors (due to the presence of clouds for example). However, when I open the geojson file it seems that the polygons are all connected forming an interlacing of lines (Figure). When there are many features in the same image it is so difficult to separate the land contours. Do you have any suggestion? I don't know if it is possible to save the detected shorelines in another file format (without closing the polygons and connecting them) and if that would solve this problem. Sorry about that ... I don't have much knowledge of Python programming. 

Thank you.

Kind regards,
Bruna

![shorelines](https://user-images.githubusercontent.com/60444738/100040543-42b7c580-2de6-11eb-9cf1-4acb49686d86.png)

**Comment by kvos** [comment]
in the new version of coastsat there is the option to save the shorelines as points instead of lines as there was this issue with the connections.
![image](https://user-images.githubusercontent.com/7217258/100040957-6584c100-2e5c-11eb-8d67-c4b7ffb88f4c.png)
choose 'points' instead of 'lines' in this cell.

**Comment by bruna-ambrosio** [comment]
Great! I'll try this.

Thanks for the help, Kilian 👍
