### ISSUE TITLE
Shoreline analysis

### ISSUE THREAD

**Issue by wreys** [kvos/CoastSat#178]
Hi Kilian,

I wonder if in the shoreline analysis (step 3 in your code) is possible to clear errors in the mapped shorelines (using GIS) before extracting the shoreline change time series?

Your code said: "If you have already mapped the shorelines, just load the output file (output.pkl) by running the section below"

filepath = os.path.join(inputs['filepath'], sitename)
with open(os.path.join(filepath, sitename + '_output' + '.pkl'), 'rb') as f:
    output = pickle.load(f) 

In this sense, if I edit/remove errors of the mapped shorelines in GIS. May I upload the geojson file (edited in Gis) instead of the .pkl' file? or is it possible to update the .pkl file when editing the geojson file in ArcGis?

I would like to clean the mapped shorelines data first in GIS and then run your step 3 (shoreline analysis).

Thanks

**Comment by kvos** [comment]
hi @wreys , yeah that should be fine. You can save the mapped shorelines (`output` variable) as a .geojson:
```
# for GIS applications, save output into a GEOJSON layer
geomtype = 'lines' # choose 'points' or 'lines' for the layer geometry
gdf = SDS_tools.output_to_gdf(output, geomtype)
gdf.crs = {'init':'epsg:'+str(settings['output_epsg'])} # set layer projection
# save GEOJSON layer to file
gdf.to_file(os.path.join(inputs['filepath'], inputs['sitename'], '%s_output_%s.geojson'%(sitename,geomtype)),
                                driver='GeoJSON', encoding='utf-8')
```
Sometimes when using 'lines' the vertices are not joined in the right order and there are some weird intersections, so maybe it's better so save as 'points'. Then you can load that geojson in QGIS/ArcGIs and edit the vertices. 
Then you will have to load the geojson file with geopandas (`gpd.read_file`), which will give you a geodataframe. The only step where you will have to code something is to convert that geodataframe into a dictionary (like the original `output` variable) that you can then feed to the shoreline analysis part. 

Just to help you can look at this function from SDS_tools.py, which converts the dictionary into geodataframe, basically you need to do the opposite (from geodataframe to dictionary). To convert the date as a string to datetime you can use `datetime.strptime(date_as_string,format)`. Also make sure to attribute a timezone to the datetimes with `pytz.utc.localize(datetime)`, otherwise it will break further down in the shoreline analysis.
```
def output_to_gdf(output, geomtype):
    """
    Saves the mapped shorelines as a gpd.GeoDataFrame    
    
    KV WRL 2018
    Arguments:
    -----------
    output: dict
        contains the coordinates of the mapped shorelines + attributes
    geomtype: str
        'lines' for LineString and 'points' for Multipoint geometry      
                
    Returns:    
    -----------
    gdf_all: gpd.GeoDataFrame
        contains the shorelines + attirbutes
  
    """    
     
    # loop through the mapped shorelines
    counter = 0
    for i in range(len(output['shorelines'])):
        # skip if there shoreline is empty 
        if len(output['shorelines'][i]) == 0:
            continue
        else:
            # save the geometry depending on the linestyle
            if geomtype == 'lines':
                geom = geometry.LineString(output['shorelines'][i])
            elif geomtype == 'points':
                coords = output['shorelines'][i]
                geom = geometry.MultiPoint([(coords[_,0], coords[_,1]) for _ in range(coords.shape[0])])
            else:
                raise Exception('geomtype %s is not an option, choose between lines or points'%geomtype)
            # save into geodataframe with attributes
            gdf = gpd.GeoDataFrame(geometry=gpd.GeoSeries(geom))
            gdf.index = [i]
            gdf.loc[i,'date'] = output['dates'][i].strftime('%Y-%m-%d %H:%M:%S')
            gdf.loc[i,'satname'] = output['satname'][i]
            gdf.loc[i,'geoaccuracy'] = output['geoaccuracy'][i]
            gdf.loc[i,'cloud_cover'] = output['cloud_cover'][i]
            # store into geodataframe
            if counter == 0:
                gdf_all = gdf
            else:
                gdf_all = gdf_all.append(gdf)
            counter = counter + 1
            
    return gdf_all
```
Let me know if you need any help. It would be a useful add-on so if it works it would be great if you could make a pull request.

**Comment by wreys** [comment]
Thanks, Kilian for your soon reply. I will make this test soon and then I will let you know how that works.
For now, I have some extra doubts:

a) Regarding the spatial resolution of S2 and L8. In the downloaded folder for the former (S2) there are 10 m, 20 m, 60 m, and for the latter, there is not information regarding spatial resolution. How could I know the spatial resolution used in each case (S2, L8)? I guess that for S2 the spatial resolution (10 m, 20 m, 60 m) depends on the available data? For L8?

b) There is possible to know the error for the shorelines detected with S2 and L8 images? For sure, it depends on the spatial resolution, but may we have an idea of the error?

c) I found some noise for the Yucatan shorelines detected, it may be related to little clouds and maybe sargassum? Not sure which other phenomenon may alter the real shoreline for a given date. That is why I had to clean the shorelines in GIS. Please see the following figures relate to these errors ..

![Profiles](https://user-images.githubusercontent.com/75654016/108536982-b01ea980-72a2-11eb-957b-9a9b9afd07ef.png)

![Time series](https://user-images.githubusercontent.com/75654016/108537007-b876e480-72a2-11eb-9e2b-8b9094d565f3.png)

**Comment by kvos** [comment]
https://www.sciencedirect.com/science/article/pii/S0378383918305313?via%3Dihub
