### ISSUE TITLE
Value Error - mapping shorelines

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat#233]
Hi, I'm having trouble when mapping shorelines in some zones of my country. It's weird because it manages to map all L5 and L7 images but it crashes at 25% of L8, in every cases. The error is: 
`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`
I saw this on issue #163 but there wasn't a solution. I also thought there could be a problem with my reference shoreline but I tried both loading the points and drawing it myself on coastsat and it's the same.
Do you have any clue what could be wrong? Because I get the feeling that it has to do with a certain image but I don't know what to do to discard it.

Thank you,
Paula.

**Comment by kvos** [comment]
hi @pgurruchaga, this has to do with the scikit-learn classifier, which cannot handle any NaN values. I'm not sure how to fix this error as it seems to be very rare and only occur occasionally on some images. Can you have a look at that image in question where it return the errors to see if there is anything obvious with the image? otherwise I can also have a look some time if you provide me with a script with your input settings so that I can reproduce the error (please limit it to where the issue is so I don't have to download all the L5, L7 and L8 that worked fine).

**Comment by pgurruchaga** [comment]
I tried by setting check detection to true and the last shoreline it's able to map corresponds to L8 2015-07-15, the next one is the one that makes it crash: L8 2015-07-17, it appears like this:
![imagen](https://user-images.githubusercontent.com/74714396/131681222-4b5bcf25-4d2f-467f-80e5-3fa9b05f00fb.png)

I looked for it in QGIS and it's obvious that something is wrong:
![imagen](https://user-images.githubusercontent.com/74714396/131681090-a78e7450-daa7-4d8a-b0c6-495392d80fb1.png)
(it's a screenshot, the satellite backgroud is not part of the image).

If that's ok with you I leave here the polygon in case you want to check:
[[-58.428,-33.97],
[-58.427,-33.909],
[-58.338,-33.91],
[-58.339,-33.971]]

Thank you for the help!

**Comment by kvos** [comment]
ok will have a look, in the meanwhile if you want to continue you can delete manually the files for that image (the pan tif, the ms tiff and the meta txt)

**Comment by kvos** [comment]
hi @pgurruchaga , found the issue and fixed it on the new version of the code. I only changed 2 lines so you can download the repo and replace SDS_shorelines.py in your coastsat folder with the new one.

The issue was that I was removing NaN values but not Inf values and both crash the classifier.

**Comment by pgurruchaga** [comment]
Hi, it worked.
Thank you so much!
