### ISSUE TITLE
Offshore bias in detection on S2 and L8 images

### ISSUE THREAD

**Issue by pgurruchaga** [kvos/CoastSat#237]
Hi. I've been facing some trouble with the shoreline detection at a certain location where there's no white water and there's dark wet sand. My problem is kinda the opposite of #177 because in my case there's an offshore bias (instead of a detection in the wet-dry sand limit). I've also read #50 but unfortunately in my case adjusting the MNDWI threshold didn't help.
Besides, I re-trained the classifier, which helped with the detection of sand pixels and the detection of some images that was wrongly at land, but it didn't solve the problem with the offshore lines.
The issue is mainly with S2 images but also in some L8 (not as evident as in S2).
I'll leave here two examples (two positions of the threshold for each one, the automatic and one modified by me) so you can see what I'm saying and perhaps give me your insight on why this is happening and what I can do. 
The images correspond to the detection with the original classifier, not the one I trained.
![Figure_1](https://user-images.githubusercontent.com/74714396/133287184-d419bdf0-526d-43c8-aa9a-61fa0a6cad67.png)
![Figure_2](https://user-images.githubusercontent.com/74714396/133287192-7dd0d18a-0f95-4b7a-b546-4ade665cefc6.png)
![Figure_3](https://user-images.githubusercontent.com/74714396/133287195-4b666c23-ebf9-4e6f-86c9-c4d6f1514f23.png)
![Figure_4](https://user-images.githubusercontent.com/74714396/133287198-fd86271c-8ef3-4eb0-86a4-b78160385810.png)

Thanks, 
Paula.

**Comment by kvos** [comment]
hi paula, the classification looks good, it just seems like that there is a very shallow, crystal clear area in front of the shoreline that is returning MNDWI values that are close to land/sand and misleading the algorithm. There are three options that I can suggest:
1. manually adjust the threshold on those images where it's completely off, or discard those images.
2. other option is to change the MNDWI, which is used to contour the shoreline, with something else that shows a better contrast between sand and water at this site. Could be NDWI (NIR-Green/NIR+Green), or SWIR only, or Red minus Blue, you will have to test this.
3. since the classification is good, you could contour the sand pixels directly, this is what was done in [CoastSat.islands](https://github.com/mcuttler/CoastSat.islands), you can try to apply that toolbox at your site.

All the best, kilian
![image](https://user-images.githubusercontent.com/7217258/133945228-3ff9bafd-a389-4665-b78b-3abaf473ec03.png)
