### ISSUE TITLE
Issue in executing SDS_preprocess.save_jpg(metadata, settings) 

### ISSUE THREAD

**Issue by MushtaqFatima** [kvos/CoastSat#252]
Dear fellows,

I have tried so many time this command "SDS_preprocess.save_jpg(metadata, settings)" in coastsat (https://github.com/kvos/CoastSat) example and it gave me same error mentioned below. Kindly guide me how to fix this issue.
Thank you

**KeyError   Traceback (most recent call last)**
~\anaconda3\envs\coastsat\lib\site-packages\matplotlib\__init__.py in __setitem__(self, key, val)
    643             try:
--> 644                 cval = self.validate[key](val)
    645             except ValueError as ve:

**KeyError: 'savefig.jpeg_quality'**

The above exception was the direct cause of the following exception:
**KeyError: 'savefig.jpeg_quality is not a valid rc parameter (see rcParams.keys() for a list of valid parameters)'**

**Comment by pvsmartin** [comment]
Hi everyone,
I've installed coastsat at least on 3 different pc's. It just work on one of them. 'savefig.jpeg_quality' is the most common error I encounter. After revising every one of the setups I think it's related with matplotlib version. I also have some trouble with the jupyter notbook version. I tried installing with and without the yml file but with the same result. At some point an error arise. 

However, I'm newbie with both anaconda and python. Last version of matplotlib given into a yml file is 3.0.3. Next step, for me, is create my own yml from alll of them available. Still, I would appreciate to know which version of Anaconda and all of the libraries used since it seems that not the lastest always works.

Still, I'm willing to learn how to use so promising tool for coastal researcher!

**Comment by kvos** [comment]
hi @MushtaqFatima and @pvsmartin , yes it  seems to be a matplotlib issue, not related to the CoastSat toolbox. can you just try to save a figure as .jpg with the coastsat environment activated:
```
import matplotlib.pyplot as plt
plt.figure()
plt.savefig('test.jpg')
```
check what version of matplotlib you have and what's the syntax for saving a jpg in that version, they may have done an update and the coastsat calls could be deprecated.

**Comment by pvsmartin** [comment]
hi @kvos, 
I'm trying to find the config or installation that works, but I tried so many of them that I don't find the correct one and I'm no able to reproduce the error. However I remember all this stuff had to do with "savefig.jpeg_quality" been deprecated with some other keywords.

About matplotlib version I have try almost all of them since 3.3.0. 

your little test worked fine, but there wasn't any non-default value, just a void figure that seems to still work with any version of matplotlig.pyplot.  So, I think the issue is somewhere else. I quote what matplotlib website tells about rcparams quality in case it's useful.
 
[https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.3.0.html?highlight=quality]
> JPEG options
> The quality, optimize, and progressive keyword arguments to savefig, which were only used when saving to JPEG, are deprecated. rcParams["savefig.jpeg_quality"] is likewise deprecated.
> 
> Such options should now be directly passed to Pillow using savefig(..., pil_kwargs={"quality": ..., "optimize": ..., "progressive": ...}).

Don't know if it helps, but I hope so.

I'll try to dig deeper

**Comment by rdgomt** [comment]
I'm also facing this issue. Not able to use CoastSat at the moment.

**Comment by rdgomt** [comment]
According to Matplotlib latest version (3.5.0) documentation:

https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html?highlight=jpeg_quality

> The quality, optimize, and progressive parameters of Figure.savefig (which only affected JPEG output) have been removed, as well as from the corresponding print_jpg methods. JPEG output options can be set by directly passing the relevant parameters in pil_kwargs.

So, removing `plt.rcParams['savefig.jpeg_quality'] = 100` in `SDS_preprocess.py` worked for me.

**Comment by kvos** [comment]
thanks @rdgomt for reporting this, will update this in the code. check it out @MushtaqFatima
