### ISSUE TITLE
Error in SDS_download.merge_overlapping_images()

### ISSUE THREAD

**Issue by 2320sharon** [kvos/CoastSat#257]
## Description
While I was downloading some data with Coast using the `` retrieve_images `` function I got an error stating that an error happened while attempting to merge overlapping S2 images. This resulted in the ``save_jpg()`` also failing to convert any of the tifs to jpgs. I am hoping to figure out two things:
 1. Why  merge_overlapping_images() broke? 
 2. Is it possible to still create jpgs using ``save_jpg()``  if ``merge_overlapping_images()`` fails for some tifs?

 I have included a screenshot of where the data I was attempting to download is located as well as the geojson for the region of interest (ROI). I have tried the same script only changing the date parameters passed to CoastSat and it works fine.  

## Error Messages
```
WARNING: there was an error while merging overlapping S2 images, please open an issue on Github at https://github.com/kvos/CoastSat/issues and include your script so we can find out what happened.
```
### Error message raised by save_jpg
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_10368\930317051.py in <module>
     23     }
     24     print(metadata)
---> 25     SDS_preprocess.save_jpg(metadata, pre_process_settings)

C:\1_USGS\CoastSeg\repos\CoastSeg_fork\Seg2Map\notebooks\coastsat\SDS_preprocess.py in save_jpg(metadata, settings, **kwargs)
    639             fn = SDS_tools.get_filenames(filenames[i],filepath, satname)
    640             # read and preprocess image
--> 641             im_ms, georef, cloud_mask, im_extra, im_QA, im_nodata = preprocess_single(fn, satname, settings['cloud_mask_issue'])
    642 
    643             # compute cloud_cover percentage (with no data pixels)

C:\1_USGS\CoastSeg\repos\CoastSeg_fork\Seg2Map\notebooks\coastsat\SDS_preprocess.py in preprocess_single(fn, satname, cloud_mask_issue)
    256         fn10 = fn[0]
    257         data = gdal.Open(fn10, gdal.GA_ReadOnly)
--> 258         georef = np.array(data.GetGeoTransform())
    259         bands = [data.GetRasterBand(k + 1).ReadAsArray() for k in range(data.RasterCount)]
    260         im10 = np.stack(bands, 2)

AttributeError: 'NoneType' object has no attribute 'GetGeoTransform'
```

## Questions
1. Any idea why ``merge_overlapping_images()`` function is failing?
2. Is the merge function failing also causing ``save_jpg()`` to fail because the filename wasn't generated in the merge function? 

## Known aspects
1. The metadata.pkl is being generated by ``retrieve_images()``, but something in merge_overlapping_images() is breaking causing the warning message to appear.
2.  All the files in metadata.pkl exist on my computer
3.  Other dates in the same region will download and merge correctly such as dates=['2015-12-01', '2016-12-31'].
4.  All the directories 10m,20m,60m, and meta were generated for S2 satellite images. They all appear to have valid contents
5. The ``save__jpg()`` method got stuck before it could create any jpg files because the "preprocessed"directory was empty
6. In the script only the first set of inputs in list_of_inputs was run before the exception was raised

## How the script works
1. Reads in the geojson file "selected_roiERROR.geojson" from the current working directory. See a screenshot of the region below.
2. The data is loaded from the file and the geometry from the geojson file is passed to CoastSat via the polygon parameter.
3. For each polygon in the geojson file CoastSat is used to retrieve and preproccess the images using save_jpg().
![selected_roi_error_geojson](https://user-images.githubusercontent.com/61564689/152891420-22c7f82b-187c-44ba-bbf2-96f6b580ce48.jpg)

## Source Code
I have included the source code as a jupyter notebook complete with all the original outputs along with the original geojson file.
[CoastSat_Error_Code.zip](https://github.com/kvos/CoastSat/files/8025854/CoastSat_Error_Code.zip)

**Comment by kvos** [comment]
hi @2320sharon , thanks for the detailed issue. There must be something playing up with the merge_overlapping function. I don't have time to troubleshoot it right now, but if you can give me your settings parameters in a txt file I will add it to my todo list.
 
In the meanwhile, please got to SDS_download.py and comment lines 284-290, then delete the entire data folder (including all downloaded images and metadata file) and restart your download without merging overlapping images. Then save_jpg should work fine.

To answer your question, yes the error in merge_overlapping and save_jpg are related, because the merge_overlapping call fails, it leaves some .tif files incomplete, so when you then call save_jpg it breaks when reading those files that were not merged properly.

**Comment by kvos** [comment]
by the way, if you'd like to have a look why `SDS_download.merge_overlapping_images()` fails for one of your polygons or some specific dates, you can have a look at the function, briefly it tries to deal with all the strange cases where the ROI is at the edge of a tile and hence overlaps with other tiles (a lot of if statements in that function). It does the following operations:
1.  For images taken at the exact same time , it takes the image with the larger footprint and deletes the other one
2. For images taken within 5 minutes of each other, there can be duplicates, triplicates or even quadruplicates! It then considers two images at a time and checks if one contains the other, in that case keeps the larger. If they are complementary (cover separate areas with some overlap), it merges them using `gdal_merge`. There are some issues with the way S2 images are cropped and these depend on the version of the Google Earth Engine API that you used to download them. Can you please let me know that version too? It could be that the new version is cropping them different, hence the error.

**Comment by 2320sharon** [comment]
> 

Thank you for answering my issue so quickly and answering all my questions.
I'll comment out those lines and hopefully, the save_jpg() will work. Thanks for explaining it so clearly.

If any of my code needs clarification feel free to ask and I'll do my best to answer!
[coastsat_error-settings.txt](https://github.com/kvos/CoastSat/files/8028736/coastsat_error-settings.txt)

**Comment by 2320sharon** [comment]
I noticed that ``SDS_download.merge_overlapping_images()`` was pretty big and didn't fully understand everything it did, so this explanation helped quite a bit thank you!

The version of ee I have installed in the environment is **0.1.256**.

**Comment by kvos** [comment]
yes `SDS_download.merge_overlapping_images()` is by far the longest function in the repo, it's just that there are some many strange cases to account for. The latest ee version I tested was 0.1.26 so could be an issue with that.

**Comment by 2320sharon** [comment]
This is great info, I didn't know about the debugging mode I could check out. Thank you again for all your help!

**Comment by 2320sharon** [comment]
Hi again Kilian,
I finally got around to debugging this script, and commenting out the lines 284-290 to download the imagery worked great! I'm now trying to run debug mode with  ```%pdb 1``` but I'm not sure exactly where or how to run it. Where are you running the command from? My logic was to run it from the console within Jupyter notebook or the anaconda terminal but I'm having difficulty getting anything to work properly meaning I'm probably doing something wrong. 

Can you walk me through your debugging process so that I can replicate it on my end? Specifically, where you are running your commands from, what commands you are running, and your code editor of choice might be helpful to know? I've been using Juptyer lab in an Anaconda environment and running all my code from within Jupyter lab.

Thank you again for all your help!

**Comment by kvos** [comment]
hi sharon, so when you ran it without lines 284-290 and then created the jpegs, were there a lot of duplicates?
so you need to import pdb, then you just run `%pdb 1` once (at the beginning of the notebook for example) and it should enter debug mode as soon as it finds an error. %something is a magic command, like you can do `%matplotlib qt` and the plots will become interactive in your notebook. The problem with `%pdb 1` is that sometimes it goes really deep into the specific functions that broke, you can do `%pdb 0` to go back to normal. You can also write pdb.set_trace() anywhere in your code and it will stop there and enter debug mode. 
I mostly use spyder and jupyter lab, spyder is good for debugging as you can check your variables and run individual lines with F9. 

another thing, usually you can predict at which coordinates there will be duplicates in the S2 archive as it is where two or more tiles overlap, you can see all the tiles here https://eatlas.org.au/data/uuid/f7468d15-12be-4e3f-a246-b2882a324f59

**Comment by 2320sharon** [comment]
Hi again Kilian,
Thank you for explaining what the command ``%pdb 1`` does; I wasn't sure if I could run it from within the notebook or if it was strictly from the command line.  That's really cool that magic commands can do that. I was able to use pdb to debug what was wrong with the code. 

I initially thought some of my .tif files didn't exist, but it turns out some of them were corrupted making it so that when
``SDS_tools.get_image_bounds()`` called them and then ``data = gdal.Open(fn, gdal.GA_ReadOnly)`` attempted to open the file (aka fn) it would fail and return data as NoneType which would cause the next line ``gt = data.GetGeoTransform()`` to fail because objects of none type have no attribute ``GetGeoTransform()``. The [official documentation for GDAL.open](https://gdal.org/tutorials/raster_api_tut.html#:~:text=In%20Python%3A,selecting%20physical%20files.) states there should be a check if the object returned by gdal.open are None because it indicates that the open has failed. 

I modified lines 720-725 in ``def get_image_bounds(fn)`` to be 

```
    data = gdal.Open(fn, gdal.GA_ReadOnly)
    # Check if data is null meaning the open failed
    if data is None:
        print("TIF file: ",fn, "cannot be opened" )
        raise AttributeError
    else:
        gt = data.GetGeoTransform()
        cols = data.RasterXSize
        rows = data.RasterYSize
        ext = GetExtent(gt,cols,rows)
    
    return geometry.Polygon(ext)```

Then in ``SDS_download.def merge_overlapping_images(metadata,inputs)``:
Any call to get_image_bounds() would have a try-except block encompassing it which would check if the attribute exception was raised. If the exception was raised then it would skip and print the name broken tif file. The idea is to process the uncorrupted tifs and just skip the corrupted ones. I'm not sure if skipping the files would break something else in the code but this solution seems to work for now.
``` try: 
            polygon0 = SDS_tools.get_image_bounds(fn_im[0][0])
            im_epsg0 = metadata[sat]['epsg'][pair[0]]
        except AttributeError:
            print("\n Error Getting the TIF skipping this iteration of the loop")    
            continue```
Also thank you for sharing the eatlas.org link. I didn't know you could predict when tiles would overlap.
Thank you again for all your help!

**Comment by kvos** [comment]
hi sharon, great that you modified that GDAL call to raise the error properly, could you please make a pull request with those changes? If you think it needs more testing you can push to the development branch, otherwise directly to master. I'm not sure if the `continue` may not break things further down, would need to check again what's going on in that loop.

I was testing your jupyter notebook that you first posted, may I know which one of the 4 polygons is causing the merge_overlapping error? and do you know around which dates it happens? like this I can narrow down the search and avoid downloading all the images. Thanks.

**Comment by kvos** [comment]
I think you found a good test for the merge_overlapping_images() function as you are right in a region of high overlap in the S2 grid, there should be quadruples in there for the most northern polygon!

![image](https://user-images.githubusercontent.com/7217258/155065413-14625346-7f4d-489e-8255-1534ec0781d6.png)

**Comment by 2320sharon** [comment]
> 

I'll see if I can figure out the specific dates that were causing the issues and provide you with them. Hopefully, I can get you the dates sometime this week.

I'll do some further testing with my modified version of the code to check for obvious problems, then submit a pull request on the testing branch. In my initial tests, it has worked so far, but I want to be sure. I'll submit a pull request on the testing branch sometime this week. I don't want to submit a pull request on the master branch yet just in case the ``continue`` statements break something else that isn't obvious.

Thank you for showing where the dataset was overlapping multiple tiles. Being able to see the issue is really helpful!

**Comment by kvos** [comment]
thanks @2320sharon!
The only issue I can foresee with `continue` is that if it skips the file that it can't open, it may leave a corrupted file there and then when running another function (like save_jpgs) it may break again. I can do some testing on your PR too.

I'm having a look at some images of your polygon from late 2018:

- some have the exact same timetag (to the closest second), like the first 4 here taken on 2018-11-01-18-55-24:
![image](https://user-images.githubusercontent.com/7217258/155423701-0b4f71b9-96ff-4a31-8f0b-a098b10623a1.png)
When they have the exact same timetag they get named dup1, dup2 all the way to dup4 during download. These are handled in the first part of `merge_overlapping_images()` (lines 722-771), this part looks at the respective footprints (with `get_image_bounds()` and keeps the image that contains all the others, and deletes the rest of the duplicates. 

You can see in this example, that this would be the first image, the rest are just different crops of the same image:
![image](https://user-images.githubusercontent.com/7217258/155424662-160c28ce-45a9-4803-a5aa-b3b7f1ad4572.png)
![image](https://user-images.githubusercontent.com/7217258/155424864-f14888fe-764e-423c-ae9a-b443e304ef19.png)
![image](https://user-images.githubusercontent.com/7217258/155424887-4682243a-2f97-4310-9085-56215be7c2ad.png)
![image](https://user-images.githubusercontent.com/7217258/155424959-c99d6f26-c4ad-4bc1-a0ea-bc60ca973b24.png)

Where it gets tricky is that the same kind of duplicates can also be a few seconds apart, for example the next 4 images, same footprints but now they don't have the same timetag:
![image](https://user-images.githubusercontent.com/7217258/155425144-d8e2f5f3-9714-4169-932d-9c6ce0c13248.png)

These are handled in the next part of `merge_overlapping_images` (lines 773-813) where the function looks to group all the images that are less than 5 minutes apart. It then goes through each pair (after line 813) and compares the footprints, if one contains the other it keeps the larger one, otherwise merges them with `gdal_merge` after some cleaning as I observed some boundary effects on some overlapping images (not the case for your ROI but we want to keep it as general as possible). When the function merges the two images, it deletes the old duplicates and creates new files with the suffix '_merged.tif'.

The function `merge_overlapping_images` is still a bit clunky and always creates issues but hopefully if we fix this issue here it should be good for a while. Luckily the Landsat crops are so much cleaner and there is no need for this, it's only for S2.

**Comment by 2320sharon** [comment]
Ah! It seems my data had a rare edge case in it by having seven duplicates. Thank you for providing the screenshots showing the problematic duplicates.

I'm not sure how exactly the lines  795-813 could rid of more than 4 images, does the line ``` if sum(pair_first == idx) == 3:`` need to be changed to a larger number? I'm a tad confused as to how to check for any more than 4 overlapping images.

As for the code, I wrote, instead of just continuing through the loop and leaving a potentially corrupted file in the directory. Do you think it's a good idea to delete the file that is suspected of being corrupted so it can't cause any problems? 

Here is the basic idea of what I'm thinking. If it finds that the file ``fn`` can't be opened with ``gdal.Open(fn, gdal.GA_ReadOnly)`` it deletes the file ``fn`` and raises an exception and still causes the continue.

```
    data = gdal.Open(fn, gdal.GA_ReadOnly)
    # Check if data is null meaning the open failed
    if data is None:
        print("TIF file: ",fn, "cannot be opened" )
        # new code to delete the corrupted file that couldn't be opened with gdal.Open
         os.remove(fn)
        raise AttributeError
    else:
        gt = data.GetGeoTransform()
        cols = data.RasterXSize
        rows = data.RasterYSize
        ext = GetExtent(gt,cols,rows)
            ```

**Comment by kvos** [comment]
yes exactly, `if sum(pair_first == idx) == 3` is when there are 4 duplicates (3 pairs, the first image being always the same, for example if the `pairs` variable contains (1,2) (1,3) (1,4) it means that images 1,2,3,4 are duplicates. This needs to be increased, maybe anything above 2.
I don't think there is any corrupted file as when I ran save_jpg on the downloaded files without merging overlapping images, it was fine for all of them. I think the issue is that the filename in `fn` doesn't exists as it's not handling so many duplicates. I can have a go at rewriting those lines (795-813) to only consider and then you can test it again, will push it to the `development` branch.

**Comment by kvos** [comment]
seems to be working on my end with a very little tweak, will push to the development today

![image](https://user-images.githubusercontent.com/7217258/155904988-bbfce451-938a-4183-a3db-e0bfe54f1ba9.png)

however it's not perfect yet as it's mostly looking at the footprints rather than merging so there are these gaps in the imagery.
![2018-11-11-19-04-04_S2](https://user-images.githubusercontent.com/7217258/155905292-51c21f36-8536-437e-a980-a846fa9ec8fb.jpg)

**Comment by 2320sharon** [comment]
I'll run some tests and see if your re-write worked. Fingers crossed!

**Comment by 2320sharon** [comment]
Good news! I tried merging the overlapping images in the dataset with the new logic you wrote and it worked like a charm! It worked even without the exception handling code I wrote. I ran save_jpg() afterward and that worked fine as well. The only notable difference I see is that save_jpg() took longer to run without excep

I also tested your code with the exception handling code I wrote and it worked great as well! Save_jpg() worked on the resulting data, so I think that means it works!

Would you still like me to merge my code containing the exception handling code into the development branch?

Thanks again for all your help!

**Comment by kvos** [comment]
yes please push those changes to the dev branch.
Before your try except it may be good to include a check on whether the filename exists, like `os.path.exists(fn)`, then if it exists you can check if it's a corrupted file.

**Comment by 2320sharon** [comment]
Hey Kilian!
I just looked over the results from my tests and yes I do have those rectangular gaps in some of the imagery. Its only a small subset of imagery.
![2021-09-26-19-04-13_S2](https://user-images.githubusercontent.com/61564689/156483545-03593ba6-98fa-4a72-83c5-4a3aebae7abd.jpg)
![2021-10-31-19-04-10_S2](https://user-images.githubusercontent.com/61564689/156483755-a19be99f-8a5e-4796-8a1e-2d8401b9556f.jpg)
![2021-12-25-19-04-11_S2](https://user-images.githubusercontent.com/61564689/156483780-7ec80b6b-eee3-4c61-a160-576d3e5614b5.jpg)

**Comment by kvos** [comment]
@2320sharon , those rectangular nodata blocks mean that something is going wrong in `merge_overlapping_images` as it should be able to reconstruct a full image with all the duplicates. I just commented a section in your branch to test out.

**Comment by 2320sharon** [comment]
@kvos working on testing it. I'll let you know how it goes with those lines commented out soon.

**Comment by 2320sharon** [comment]
@kvos 
Sorry for responding so late. I tested the merge overlapping code with the lines you commented out and I'm still getting the issue with some of the images having a chunk missing. I'm not quite sure why.
![coastsat_missing_chunks](https://user-images.githubusercontent.com/61564689/160444898-4d859d42-6554-40ad-966f-cd4bd1222d85.jpg)
.

**Comment by kvos** [comment]
ok thanks for testing that @2320sharon , it doesn't look like it improved at all. Will uncomment and go ahead with your original PR, not sure which it's missing that corner but we will find out one day :)

**Comment by kvos** [comment]
actually @2320sharon , if it doesn't take too much effort for you to run a last test, I commented out more stuff in your branch, could you please try it again to run the merge_overlapping_images() on your downloaded images to see if this helps removing that black corner? thanks very much!

**Comment by 2320sharon** [comment]
So I ran the latest code twice in two different environments that I install coastsat in and I got the same results, unfortunately. A portion of the jpgs is still missing.

**Comment by kvos** [comment]
ok I reverted back to the original PR and merged into the dev branch, great thanks Sharon.

**Comment by 2320sharon** [comment]
Awesome! Thank you for all your help in solving this issue. 👍
