### ISSUE TITLE
Some problem - Messages during running example 

### ISSUE THREAD

**Issue by hamidj2019** [kvos/CoastSat#28]
Hi Kilian,

I have set up this CoastSAT after our previous discussions. I have been trying to use Jupitor and look at the example to be able to fully capture what is going on. I received the following messages. part a and part b. I was wondering if somebody can advise what is going on?
Is this on the right track or?

![part a](https://user-images.githubusercontent.com/51834824/61995175-87d4b780-b039-11e9-9f3f-72c528720b18.JPG)

![part b](https://user-images.githubusercontent.com/51834824/61995179-8dca9880-b039-11e9-9c97-eba3a77876d1.JPG)

Thanks for your cooperation and interaction in advance.
Best wishes

**Comment by hamidj2019** [comment]
Hi Kilian,

Could you please advise about the message above?

**Comment by kvos** [comment]
hi @hamidj2019 , this means that the coastsat environment has not been setup properly and it cannot initialise the google-earth-engine package. Did you follow step 1.2 in the README and activated the gee python API? in that step you will have to sign in with a gmail account

**Comment by hamidj2019** [comment]
Hi Kilian,
Thanks for your input. In response to your question, Yes, we did that. I again tried and followed the same procedure but the same messages appears. Any input?

Best wishes,

**Comment by kvos** [comment]
ok please try this:
- open anaconda prompt
- `conda activate coastsat`
- `python`
- `import ee`
- `ee.Initialize()`
So we can check if the gee python api package is installed correctly.

**Comment by sepaas2019** [comment]
Hi,
Thanks for your previous input. 
I have tried to modify the example file and input the coordinates of the region of interest.
I got the following message. I would appreciate your input on how to solve the issue:

Unreadable Notebook: C:\Users\...\CoastSat-master\CoastSat-master\example_jupyter_Copy1.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...')

**Comment by sepaas2019** [comment]
Q2. By the way, we also tried to use a finer mesh but somewhere during the process I realized that CoastSat modifies the coordinates....which I found a bit strange...Is this normal?

**Comment by kvos** [comment]
@sepaas2019  and @hamidj2019 , for me (or others) to help you with these issues, it would be great if you could provide more details about the problems that you are having:
- introduce the problem
- provide enough information so that other can reproduce the problem
- include your settings parameters and the code that you are running

thanks,
kilian

**Comment by sepaas2019** [comment]
Question about the # region of interest (longitude, latitude)
It says in the example that it should be a polygon. 
Are the points should be "ONLY" the vertices of the region/polygon? or can they be vertices of the corners of the polygon + several points on each side of the polygon? I have about 100 pairs (longitude, latitude) that simply define the region as a boundary. 
Your insight will be appreciated to clarify how exactly the code is defined in CoastSAT.

**Comment by kvos** [comment]
this is how you should input your coordinates:
```
polygon = [[[151.301454, -33.700754],
            [151.311453, -33.702075],
            [151.307237, -33.739761],
            [151.294220, -33.736329],
            [151.301454, -33.700754]]]
```
- 5 pairs of coordinates, first coordinate is always LONGITUDE
- Coordinate system should be WGS84 spherical
- You start at one edge of your rectangle and enter the pair of coordinates in the clockwise direction, the last pair of coordinates is the same as the first one
- Only rectangles are accepted.

**Comment by sepaas2019** [comment]
Hello kilian,

Thanks for your input. However, I would need to get a full clarification on one thing. In the code there is a part for the region of interest named as polygon. So it should be a rectangle?
Since it was written a polygon we had the impression that the coastal area can be defined as a polygon. Could you please fully clarify this?
I have used a set of coordinates that represent a polygon and not necessary a rectangle.
If yes, that is good.
If not, does it mean that we need to divide the coastal area to many rectangle area? This will add to the work we need to do significantly.
Best regards

**Comment by kvos** [comment]
yes you are right, you don't need to input a rectangle, just a polygon with 4 vertices in clockwise order. Then the cropped image will be a rectangular however.

**Comment by sepaas2019** [comment]
Hello, let us say if the to talk region of interest is like a L-shape. Then it is not possible to use just a rectangle or a polygon with four vertices only as it can be imagined that if it crops it as you said we might loose some information (just a speculation). I have the closed loop/polygon of the total coast line but it is about 100 points/vertices. Could we use all these points? 
Will your code handle them okay? - from the view point of correct processing in the next steps?
Also could you send us a part of your Python code so that I can review the code and see how exactly these things have been defined. If possible it will be just nice but it is not required if it is not possible.

**Comment by kvos** [comment]
Only 5 pairs of coordinates are accepted, the last one being the exact same as the first one, more than 5 vertices will result in an error. It's fine to have a larger area than your shoreline in the image, you can define a reference shoreline in one of the next steps to focus the detection on that L-shaped shoreline.
