### ISSUE TITLE
Earthengine authenticate - Error 400 

### ISSUE THREAD

**Issue by Marcan-Graffin** [kvos/CoastSat#293]
Hi all,

I recently started using CoastSat on my lab servers instead of my own laptop. I created the environment as explained in the README. But when I typed the _earthengine authenticate_ command, a Google window popped up, stating: 
"Erreur 400 : invalid_request
The version of the app you're using doesn't include the latest security features to keep you protected. Please make sure to download from a trusted source and update to the latest, most secure version. "

Has anyone encountered this problem?

Thanks, Marcan

**Comment by kvos** [comment]
I haven't encoutered this. Can you tell me which version you have of th earth-engine api?
do `import ee` and then `ee.__version__`
could be that you have a version that is to old, in that case `conda update earthengine-api` should fix it

**Comment by Marcan-Graffin** [comment]
Hi, thanks for your answer. The issue is now solved !
After updates my earthengine-api version is **0.1.317**.

It was indeed needed to upload earthengine-api and I also had an issue with gcloud who was not installed correctly.

**Comment by smuyuan** [comment]
> Also encountered similar problems, when installing the old version of Coastsat (released in 2020), the error was 'Error 400' (A web browser could open, but I could not login due to Error 400); when installing the latest version, the error was 'Exception: gcloud failed'. The above two errors both occurred after typing 'earthengine authenticate'.

**Comment by maryl0189** [comment]
Hi, everyone

I also encountered similar problems, too. I had installed the old version of Coastsat (released in 2021), the error was 'Error 400' (A web browser could open, but I could not login due to Error 400); when installing the latest version of earthengine , the error was 'Exception: gcloud failed'. The above two errors both occurred after typing 'earthengine authenticate'.

GEE for 0.1.236
![image](https://user-images.githubusercontent.com/100199751/180592441-d0a21ebd-18a7-4a57-97ec-c23c07ee3094.png)
GEE for 0.1.317
![image](https://user-images.githubusercontent.com/100199751/180592558-cb243f3a-3745-49dc-b149-502574922a87.png)

Do anyone have any suggestions?
Thank you in advance for your help.

**Comment by kvos** [comment]
there is another issue explaining how to install gcloud #291

**Comment by maryl0189** [comment]
Hi kvos, thank you very much for the information,
The gcloud CLI installation was possible, I used GEE for 0.1.317, and now can find earthengine using coastsat like before

**Comment by Student-chuka-2020** [comment]
what is earthengine-api and how should i go about it, which is the for the recent coast sat
at
