### ISSUE TITLE
Issue of gcloud not found after installation

### ISSUE THREAD

**Issue by safnasebu** [kvos/CoastSat#348]
raise Exception('gcloud command not found. ' + tip) from e
Exception: gcloud command not found. Please ensure that gcloud is installed.

**Comment by bagussatya** [comment]
same here

**Comment by bagussatya** [comment]
found the solution, just downgrade the earthengine-api libs, mine from 0.1.330 then downgraded to 0.1.329 works

**Comment by kvos** [comment]
interesting, did you try installing gcloud separately as explained in the README installation section?

**Comment by bagussatya** [comment]
Yes, I did that already, but when I try to run the "earthengine authenticate" command the "gcloud command not found" appear so when i tried to downgrade the earthengine-api version to 0.1.329 it worked

**Comment by GEvs45** [comment]
How do you downgrade earthengine-api to 0.1.329? Thanks!

**Comment by bagussatya** [comment]
simply using pip, 
pip install earthengine-api==0.1.329

**Comment by GerbenRuessink** [comment]
Same happened to me. After installing gcloud, "earthengine authenticate" worked only after I had downgraded earthengine-api to 0.1.329 (in my case from 0.1.331).

**Comment by JPPereira93** [comment]
> simply using pip, pip install earthengine-api==0.1.329

Thanks, been searching for the solution for about 6 hours lol

**Comment by kvos** [comment]
ok thanks everybody for reporting a solution. It's a tricky problem, by forcing `earthengine-api` to a specific version (like 0.1.329) we may get stuck in the future as sometimes the new releeases of the API are not backwards compatible. I will just write in the documentation that if an error is raised because `gcloud` is not recognised, it can be fixed by downgrading to `earthengine-api` to 0.1.329.

**Comment by bagussatya** [comment]
Thanks!
