### ISSUE TITLE
Question regarding Min and Max Values of Settings?

### ISSUE THREAD

**Issue by 2320sharon** [kvos/CoastSat#352]
Hey Killian,

CoastSat is working great! I just have a question about the recommended minimum and maximum values of the parameters: `dist_clouds`,`min_beach_area`,`buffer_size`,`min_length_sl`,`max_dist_ref`, and `along_dist`. I'm trying to build some sliders that will allow users to control the value of these parameters but I don't know what the minimum and maximum values for each of these parameters should be.  Do you have any rules to recommend a value for each of these parameters? For instance, if the shoreline is relatively straight without many coves or land jettisons does this impact the recommended value of `buffer_size`? My goal is to help the user understand how they should adjust each slider depending on the type of landforms present in their imagery. This will hopefully make it easier to detect shorelines in imagery if the user knows what parameters to change. 

Thank you again for all your help in the coastseg project!

**Comment by kvos** [comment]
hey sharon, love this post, that sounds amazing to have sliders for these parameters!
I can give you some ballpark values for the extremes:
-`dist_clouds`: basically depends on how much data you are ready to sacrifice vs false detections you can handle. 
Minimum 100m (you will get more shoreline data but the cloud shadows could span more than 100m and then you have false detections). Maximum 300m, this is rather conservative as any shoreline point within 300m of a cloud pixel will be removed. I would put default as 300m and let users decrease it if they're after more data.
- `min_beach_area`: Minimum 1000 sqm (~5 connected pixels at 15m/pixel), very narrow beach. Maximum 10000 sqm (~50 connected pixels). Default should be  4500-5000 which is 20 connected pixels. I guess you could also let the slider go down to 0, which means leave the sand class as it is.
- `buffer_size` has been deprecated as it was doing the same thing as `max_dist_ref` for the reference shoreline. `max_dist_ref` defines the buffer around the reference shoreline that is considered when mapping the shoreline. This buffer ideally should include sand, white-water and water pixels. How wide the buffer is depends on the shoreline variability and on the width of the surfzone at the site. For example, if the beach is expected to move 300m over 35 years, then you want to have 'max_dist_ref' at least of 150-200m otherwise you won't be able to capture the full variability, as it will go outside of the buffer. Same applies for sites with a large tidal range, the intertidal zone could be 100s of metres so the buffer needs to be large enough to capture this. So I would say minimum = 50m for a microtidal low-energy beach, 100m for a microtidal wave-dominated beach, 150 m for mesotidal beach like northern california and maximum 300-400 m for a macrotidal beach or beach with a strong trend over the study period. Default 100 m. 
- `min_length_sl`: default 500m. If the beach is smaller than 500m then you need to adjust otherwise it won't map the shoreline.  Maybe minimum 200m and maximum 1000m.
- `along_dist`: this is only used when computing the intersections with the transects (not for shoreline mapping itself). This parameter will also depend on tidal range and alongshore-variable features on the beach. Default 25m (takes the average shoreline position 25m each site of the transect). For mesotidal sites that have more complex alongshore-features then it could be increased up to 50 or 100 to take a large portion of the beach to average out cusps, intertidal bars etc. I would say minimum 10m, default 25m and maximum 100m.

I hope this helps, let me know if other questions. The most important is clearly `max_dist_ref`.

I tried to describe the effect of each parameter in the README if you need more info: 
![image](https://user-images.githubusercontent.com/7217258/202590117-f03f6770-0ec4-438e-a49e-24536d91c0d5.png)

**Comment by 2320sharon** [comment]
Hey Killian,

Wow! Thank you for such a detailed and informative response. This is going to make building the sliders a total breeze. I really appreciate you taking the time to explain each parameter with such detail especially `max_dist_ref`, which was a bit confusing for me. I'll keep you posted on the progress of the sliders. Thank you again for all your help!
