### ISSUE TITLE
Using non-satellite imagery

### ISSUE THREAD

**Issue by kcoastal1** [kvos/CoastSat#37]
Hi Kvos,

We regularly receive high resolution geo-referenced aerial survey information and overtime we  have built up quite a database of information. 

Is it possible to include non-satellite project specific imagery in the shoreline analysis process? 

Kudos on such a great project. Digitising shorelines and accessing decent satellite imagery use to take up quite a bit of my time so its exciting to see such great developments being made.

**Comment by kvos** [comment]
hi @kcoastal1,
If you want to map shorelines automatically on aerial photographs, you may need to adapt the code so that it works with your new sensor (different format, metadata...etc). 

One issue you may encounter is that on aerial photographs (which are usually only RGB) you may not have any infrared band, which are used in the shoreline detection algorithm currently implemented in CoastSat. 

But you can use the same thresholding algorithm on another band, for example @mitchharley uses the Red - Blue colour space to automatically map shorelines on RGB images in his [CoastSnap ](https://github.com/Coastal-Imaging-Research-Network/CoastSnap-Toolbox) toolbox. 
Here's a figure (Fig. 7) from his paper on CoastSnap (https://doi.org/10.1016/j.coastaleng.2019.04.003):

![1-s2 0-S0378383918304551-gr7_lrg](https://user-images.githubusercontent.com/7217258/66356749-d72f5080-e9b7-11e9-9ae5-f67a29319b72.jpg)


If you can integrate aerial photographs in the CoastSat workflow make a pull request as that would be much appreciated by the users!
