### ISSUE TITLE
some mistakes happened when "Activate Google Earth Engine Python API"

### ISSUE THREAD

**Issue by Philip125** [kvos/CoastSat#40]
Hi Kilian, Shanghai from China here.

Thank you very much and the free tools provided by your team.

I am trying to run your script but after I copy the authorization code into the Anaconda terminal , it says "NameError:name "urllib2"is not defined"and"TimeoutError:[WinError 10060] The connection attempt failed because the connected party did not respond correctly after a certain period of time or the connected host did not respond.". 

For programming, I am just a rookie just getting started.I don't know if the reason is because I am online in China...Can you help me ?

Sincere regards!!

**Comment by kvos** [comment]
hi @Philip125 , I have never seen this error before but let's see if it can be fixed:
- first thing to try would be to deactivate any firewalls and run `earthengine authenticate` again
- the urllib2 error is strange, because the coastsat environment should have urllib3 instead. Maybe there is a package that is outdated so you can try to update the environment as follows:
1. run `conda clean --all` on the anaconda prompt
2. replace the content of your environment.yml file with this (no version numbers so it pulls that latest):
```
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - matplotlib
  - earthengine-api
  - gdal
  - geopandas
  - pytz
  - scikit-image
  - scikit-learn
  - shapely
  - spyder
  - notebook
```
3. Install the coastsat environment again using this new environment.yml file, running `conda env create -f environment.yml -n coastsat`
4. `conda activate coastsat` and run `earthengine authenticate` again

**Comment by Philip125** [comment]
Hi @kvos, Thank you for your timely reply and kind help, I am very embarrassed to reply to you for so long. Because I was busy with the midterm exam... Yesterday I tried it again and it was a amazing success.（Laughing face）I think Maybe because I changed a new VPN？
Anyway, once again, express my gratitude for your help!

**Comment by kvos** [comment]
ok good to hear @Philip125 , so did you have to re-install the environment or no need for that?

**Comment by kvos** [comment]
closing this issue as it is solved
