### ISSUE TITLE
Zero Point and Shoreline Change Rates

### ISSUE THREAD

**Issue by csmall42** [kvos/CoastSat#405]
Hi There,

I’ve been following along with CoastSat for a bit now and have been able to implement it for a couple of sites, it’s a great tool! I have what I believe is a simple question that has likely just come about from me overcomplicating it in my head. 

When the shoreline change along each transect is calculated/plotted (example image below from your tutorial), what does the zero point represent? I’m not following along with how the distance above/below zero is found. Is it based on the distance from the reference shoreline?

![CoastSat_TransectChange_Example](https://user-images.githubusercontent.com/65727937/236475615-7a76409d-412a-4b3f-a0e8-ea33245995ea.png)

Also, another question if you don’t mind is related to calculating the shoreline change rate along a given transect from the outputs. I see on the website the actual trend (m/yr) along each shore perpendicular transect is shown. I’ve use DSAS to do this in the past but was wondering if it can be done directly with CoastSat? I'm guessing the output csv file could be used for this?
 
I realize these are likely simple questions but I appreciate you taking the time to address them! Alternatively, if there is a user manual of sorts you could provide/point me to I’m happy to read through that.

Thanks in advance!

**Comment by kvos** [comment]
@csmall42 yes if you follow how the plot is made, the mean position is subtracted that's why it oscillates around 0. You can also plot the absolute distance to the origin of the transect. Long-term trends can be calculated directly on the raw shoreline data but because it is not evenly sampled, I recommend to compute seasonal averages first and then calculate the long-term trend on the seasonally-averaged shoreline time-series to have a more homogeneous temporal resolution (otherwise your trend will be biased towards the end of the record where there is more data)

**Comment by csmall42** [comment]
@kvos apologies for my delay in getting back, but awesome thanks so much for the clarification! That also makes a lot of sense about finding the seasonal averages first to avoid having the bias towards the end.

Thanks again for your help!
