### ISSUE TITLE
Retrieve 2D tidally-corrected shoreline as shp/geojson

### ISSUE THREAD

**Issue by czarnes22** [kvos/CoastSat#495]
Hi Kilian, 
This is a very loose question from a series of curiosities. Can the coastline be retrieved (in shp line) from the CoastSat tool only after sea level-related correction? Have You and Your team considered this question? As You can see from the graphs before and after the correction, the changes are not drastic, but they also affect the calculation of the rate of these changes in different sections of the coast. What do You think about this? Sorry for the inconvenience
Thanks, 
Kamil

**Comment by kvos** [comment]
hi @czarnes22 , I cannot see any graphs in your post, did you intend to add graphs?
So you can retrieve the raw shoreline as shapefile, it is currently saving as geojson by default but you can go in the code and change the extension to shp.
Getting the tidally-corrected shoreline is more complicated. To translate the shoreline seawards (high tide) or landwards (low tide) you need to know the orientation of seawards/landwards. That's why we work with shore-normal transects and do the tidal correction along each transect. What you could do is to use a dense set of transects (every 30m or so) and then reconstruct the line from the transect time-series. I know Sean Vitousek from USGS does this in his work, using a Matlab script though. If you figure out something in Python, feel free to make a pull request.
Cheers,
Kilian

Good luck
