### ISSUE TITLE
potential cloud mask issue? 

### ISSUE THREAD

**Issue by mcuttler** [kvos/CoastSat#5]
@kvos  - 

See attached for quick test case from south coast of WA (Parry's Beach, near Denmark). Seems like the beach pixels in the majority of the images are being masked out (e.g., 2015-02-23_L8 and 2015-10-21_L8), however, some images are still processed normally (e.g. 2016-06-01_L8). 

I have tried this for a few other locations along the SW coast and seem to get the same issue, but have yet to see this for other test locations (i.e. Mandurah). Maybe an issue with how the cloud mask is applied or calculated ? 

[SouthCoast_WA_examples.zip](https://github.com/kvos/CoastSat/files/2849697/SouthCoast_WA_examples.zip)

**Comment by kvos** [comment]
Hi Mike,

I had a look at the first Landsat 8 image in the folder (2015-02-23_L8) at this is the Quality Assessment image that comes with the image (computed by the data provider USGS).  

![figure_2](https://user-images.githubusercontent.com/7217258/52547153-81e77300-2e19-11e9-9c13-53d3b9773b7e.png)

It seems like many sand pixels are identified as "high confidence cloud" (in light blue). The red pixels in the cloud mask are "cloud shadow" which I do not mask in the code. Below is the RGB image for your reference.
![2015-02-23_l8](https://user-images.githubusercontent.com/7217258/52547161-99bef700-2e19-11e9-85e1-732732b6c3eb.jpg)

This Excel spreadsheet [L8 QA Value Interpretation.xlsx](https://github.com/kvos/CoastSat/files/2849925/L8.QA.Value.Interpretation.xlsx) indicates all the values that the cloud mask can take and highlighted in yellow the ones that I am masking in Landsat 8 images: [2800, 2804, 2808, 2812, 6896, 6900, 6904, 6908]. 
You can find more information on the interpretation of Landsat QA images here: https://landsat.usgs.gov/collectionqualityband

On the USGS website they also talk about the limitations of their cloud masking algorithm CFMASK (https://landsat.usgs.gov/what-cfmask). **"Users should be aware that, like other cloud algorithms, CFMask may have difficulties over bright targets such as building tops, beaches, snow/ice, sand dunes, and salt lakes."**

Does this issue occur on many of the images? I have seen before some patches of white-water identified as clouds but it was not a major problem for the shoreline detection.

You can manually remove the value **2800** (which corresponds to high confidence cloud) at line 52 in _SDS_preprocess.py_  . However, you may not be able to identify real clouds on other images.

If anyone knows about a cloud masking algorithm that would work better than CFMASK for the detection of beaches (bright features), it would be great to test it!

**Comment by mcuttler** [comment]
Hi Killian - 

Thanks for the info! 

This seems to be an issue for a vast majority of the images I tested this morning for the south coast of WA (images ranged downloaded between January 2015 to present).  Interestingly, this wasn't an issue for my tests at Mandurah...

How are you examining the QA image - through the USGS ArcGIS toolbox or is there a python script within CoastSat tools? Would be good to have a more thorough look through the problematic images and see if it's the same cause for all of them.

**Comment by kvos** [comment]
Hi mike,

I have proposed a solution to avoid having pixels corresponding to beach features in the cloud mask (and updated the development branch). The idea is to remove from the cloud mask the pixels that form very thin linear features. In fact the real clouds usually form compact patches of pixels, while the beach, as we can see in your images, is mostly a linear feature. I have added lines of code (Line 61-67) to the function that creates the cloud mask (first function in _SDS_preprocess.py_):
```
def create_cloud_mask(im_qa, satname):
    """
    Creates a cloud mask using the information contained in the QA band.
    
    KV WRL 2018
    
    Arguments:
    -----------
        im_qa: np.array
            Image containing the QA band
        satname: string
            short name for the satellite (L5, L7, L8 or S2)
            
    Returns:
    -----------
        cloud_mask : np.array
            A boolean array with True if a pixel is cloudy and False otherwise
    """
    
    # convert QA bits (the bits allocated to cloud cover vary depending on the satellite mission)
    if satname == 'L8':
        cloud_values = [2800, 2804, 2808, 2812, 6896, 6900, 6904, 6908]
    elif satname == 'L7' or satname == 'L5' or satname == 'L4':
        cloud_values = [752, 756, 760, 764]
    elif satname == 'S2':
        cloud_values = [1024, 2048] # 1024 = dense cloud, 2048 = cirrus clouds
    
    # find which pixels have bits corresponding to cloud values
    cloud_mask = np.isin(im_qa, cloud_values)
    
    # remove cloud pixels that form very thin features. These are beach or swash pixels that are 
    # erroneously identified as clouds by the CFMASK algorithm applied to the images by the USGS.
    if sum(sum(cloud_mask)) > 0 and sum(sum(~cloud_mask)) > 0:
        elem = morphology.square(3) # use a square of width 3 pixels 
        cloud_mask = morphology.binary_opening(cloud_mask,elem) # perform image opening
        # remove objects with less than 25 connected pixels
        morphology.remove_small_objects(cloud_mask, min_size=25, connectivity=1, in_place=True)
    
    return cloud_mask
``` 
It uses morphological operators to erode the edges of the cloud patches (removes them if they are very thin) and remove the objects that have less than 25 connected pixels (generally not clouds). This is how the previous image looks now:
![2015-02-23_l8](https://user-images.githubusercontent.com/7217258/52561557-d574b380-2e4f-11e9-8090-1c2bd3d0d0be.jpg)
you could increase the minimum number of connected pixels (**min_size** at Line 67) in order to remove that last patch of misclassified pixels.

If you'd like to explore this issue more and plot the variables **im_qa** and **cloud_mask**, you can add the following lines (at Line 60).
```   
plt.figure()
plt.imshow(im_qa, cmap='jet')
plt.figure()
plt.imshow(cloud_mask)
```
and call `SDS_preprocess.save_jpg(metadata, settings)`  in main.py for the images that you'd like to analyse.

Let me know if this helps for images of the south coast of WA,

**Comment by mcuttler** [comment]
Hey Killian - 

That's awesome, thanks! Will give this a go today or tomorrow and let you know, but looks like it should do the trick!
