### ISSUE TITLE
GeoJSON output file open in a GIS software issue

### ISSUE THREAD

**Issue by sppolizel** [kvos/CoastSat#71]

**Comment by kvos** [comment]
hi @sppolizel , the issue here is that the shoreline points are being converted to a LineString in the geojson file so it's basically joining all the point with segments. If you define a `reference_shoreline` this would help a lot for the visualisation. Otherwise you can manipulate the mapped shorelines directly in python.

**Comment by sppolizel** [comment]
hi Kilian, many thanks for you prompt reply and for the explanation. I've realised that after seeing in detail the mapped shorelines files. I also define a reference shoreline and the results were simpler (less features mapped). Thanks again.

**Comment by kvos** [comment]
ok all good then, I will close this issue

**Comment by natarslan** [comment]
I know this issue is closed but I would appreciate some more clarification on what it is to add a  reference shoreline.
