### ISSUE TITLE
Not getting images with ROI in KML format

### ISSUE THREAD

**Issue by rdgomt** [kvos/CoastSat#93]
**Describe the bug**
The program seems to run infinitely on the first cell when I set a ROI with a KML polygon. It does not occur when coordinates are set explicit. I've tried to use other folders for the input file but the problem persists.

**To Reproduce**
I just want to use a KML file as my input polygon.
```
kml_polygon = os.path.join(os.getcwd(), 'input_polygons', 'TRECHO_A.kml')
polygon = SDS_tools.polygon_from_kml(kml_polygon)
```

**Expected behavior**
I expect that the program check images available within the ROI.

**Screenshots**
![Sem título](https://user-images.githubusercontent.com/23437436/81947860-6d26fb80-95d7-11ea-9e42-93be01269ade.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CoastSat Version: commit 019f45

**Additional context**
KML file: https://drive.google.com/file/d/103futKxbJ0VQ_rCQd-8--6gtNYjrhpPX/view?usp=sharing

**Comment by kvos** [comment]
hi @rdgomt , it seems there is an issue with the format of your KML. I have drawn the polygon on Google MyMaps and then exported it as .KML, maybe try doing it this way. Otherwise you can modify the code that loads it. The input needs to be a set of 5 pairs of coordinates where the last point is the same as the first one, you can obtain this as you prefer (KML, geojson, shapefile...etc)

**Comment by rdgomt** [comment]
I've tried with QGIS and Geojson.io KML files, but it's working only with a Google MyMaps KML.

**Comment by kvos** [comment]
that's strange, there must be something going on with the way the KML files are generated... I guess you can also write a function to load a .geojson directly with geopandas instead of KML
